version: 1
include:
  - "*"
headers:
  - source: "/src/*"
    headers:
      - key: "Cache-Control"
        value: "no-cache, no-store, must-revalidate"
  - source: "/src-index.html"
    headers:
      - key: "Cache-Control"
        value: "no-cache, no-store, must-revalidate"
  - source: "/source-index.html"
    headers:
      - key: "Cache-Control"
        value: "no-cache, no-store, must-revalidate"
  - source: "/bundle.js"
    headers:
      - key: "Cache-Control"
        value: "no-cache, no-store, must-revalidate"
  - source: "/*"
    headers:
      - key: "Cache-Control"
        value: "public, max-age=3600"
  - source: "/index.html"
    headers:
      - key: "Cache-Control"
        value: "no-cache, no-store, must-revalidate"
